# This is a basic workflow to help you get started with Actions

name: Font Generator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # install python3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.7

      # Runs a single command using the runners shell
      - name: Install requirements
        run: |
          pip install fontmake
          pip install git+https://github.com/typemytype/drawbot

      # Runs a set of commands using the runners shell
      - name: Generating fonts
        run: |
          for path in ufo/*.ufo; do
            fontmake -u $path -o otf --output-dir binaryFiles
          done

      - name: DrawBot stuff
        run: |
          python specimen/specimenMaker.py
          python specimen/socialMedia.py

      - name: Upload generated fonts
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Generated Fonts
          # A file, directory or wildcard pattern that describes what to upload
          path: binaryFiles

      - name: Upload specimen
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Specimen
          # A file, directory or wildcard pattern that describes what to upload
          path: specimen.pdf

      - name: Upload Social Media gifs
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Social Media
          # A file, directory or wildcard pattern that describes what to upload
          path: socialMedia

